### PR TITLE
fix: Reliably determine that an AppMap index is up-to-date

### PR DESCRIPTION
**Pull request by kgilpin**
## Status

build passes
Need to test and verify with Solidus environment 

# Description 

First, don't use ctime to determine when a file is created - because that's not what it does. In fact, it's:

[Time when file status was last changed (inode data modification)](https://nodejs.org/api/fs.html#stat-time-values)

Second, move the normalized AppMap file into place after writing the mtime file, so that when the indexer is triggered by the new/updated AppMap file, it will always find an mtime file that tells it that the index is already up-to-date.

Here's what it looks like in practice:

```
Fingerprint is up to date. Skipping...
/Users/kgilpin/source/land-of-apps/solidus/api/tmp/appmap/rspec/Spree_Api_ProductsController_as_a_normal_user_tracking_is_disabled_still_displays_valid_json_with_total_on_hand_Float_INFINITY.appmap.json created at 1655431191428, indexed at 1655431116186
Read 342167 bytes
Computed digest for packages
Computed digest for labels
Computed digest for classes
Computed digest for httpServerRequests
Computed digest for sqlTables
Computed digest for httpClientRequests
Computed digest for sqlNormalized
Computed digest for info
Computed digest for packageDependencies
Computed digest for update
Computed digest for trace
Computed digest for classDependencies
AppMap changed: /Users/kgilpin/source/land-of-apps/solidus/api/tmp/appmap/rspec/Spree_Api_ProductsController_as_a_normal_user_tracking_is_disabled_still_displays_valid_json_with_total_on_hand_Float_INFINITY.appmap.json
Fingerprinting /Users/kgilpin/source/land-of-apps/solidus/api/tmp/appmap/rspec/Spree_Api_ProductsController_as_a_normal_user_tracking_is_disabled_still_displays_valid_json_with_total_on_hand_Float_INFINITY.appmap.json
/Users/kgilpin/source/land-of-apps/solidus/api/tmp/appmap/rspec/Spree_Api_ProductsController_as_a_normal_user_tracking_is_disabled_still_displays_valid_json_with_total_on_hand_Float_INFINITY.appmap.json index version is 1.1.2
/Users/kgilpin/source/land-of-apps/solidus/api/tmp/appmap/rspec/Spree_Api_ProductsController_as_a_normal_user_tracking_is_disabled_still_displays_valid_json_with_total_on_hand_Float_INFINITY.appmap.json created at 1655431191868, indexed at 1655431191868
Fingerprint is up to date. Skipping...
AppMap changed: /Users/kgilpin/source/land-of-apps/solidus/api/tmp/appmap/rspec/Spree_Api_ProductsController_as_a_normal_user_finds_a_product_by_slug_first_then_by_id_example_at_Users_kgilpin_rbenv_versions_2_6_6_lib_ruby_gems_2_6_0_gems_appmap-0_83_3_lib_appmap_rspec_rb_233.appmap.json
Fingerprinting /Users/kgilpin/source/land-of-apps/solidus/api/tmp/appmap/rspec/Spree_Api_ProductsController_as_a_normal_user_finds_a_product_by_slug_first_then_by_id_example_at_Users_kgilpin_rbenv_versions_2_6_6_lib_ruby_gems_2_6_0_gems_appmap-0_83_3_lib_appmap_rspec_rb_233.appmap.json
/Users/kgilpin/source/land-of-apps/solidus/api/tmp/appmap/rspec/Spree_Api_ProductsController_as_a_normal_user_finds_a_product_by_slug_first_then_by_id_example_at_Users_kgilpin_rbenv_versions_2_6_6_lib_ruby_gems_2_6_0_gems_appmap-0_83_3_lib_appmap_rspec_rb_233.appmap.json index version is 1.1.2
/Users/kgilpin/source/land-of-apps/solidus/api/tmp/appmap/rspec/Spree_Api_ProductsController_as_a_normal_user_finds_a_product_by_slug_first_then_by_id_example_at_Users_kgilpin_rbenv_versions_2_6_6_lib_ruby_gems_2_6_0_gems_appmap-0_83_3_lib_appmap_rspec_rb_233.appmap.json created at 1655431192376, indexed at 1655431111421
Read 793401 bytes
Computed digest for classDependencies
Computed digest for httpServerRequests
Computed digest for packages
Computed digest for info
Computed digest for classes
Computed digest for sqlNormalized
Computed digest for httpClientRequests
Computed digest for update
Computed digest for packageDependencies
Computed digest for sqlTables
Computed digest for labels
Computed digest for trace
AppMap changed: /Users/kgilpin/source/land-of-apps/solidus/api/tmp/appmap/rspec/Spree_Api_ProductsController_as_a_normal_user_finds_a_product_by_slug_first_then_by_id_example_at_Users_kgilpin_rbenv_versions_2_6_6_lib_ruby_gems_2_6_0_gems_appmap-0_83_3_lib_appmap_rspec_rb_233.appmap.json
Fingerprinting /Users/kgilpin/source/land-of-apps/solidus/api/tmp/appmap/rspec/Spree_Api_ProductsController_as_a_normal_user_finds_a_product_by_slug_first_then_by_id_example_at_Users_kgilpin_rbenv_versions_2_6_6_lib_ruby_gems_2_6_0_gems_appmap-0_83_3_lib_appmap_rspec_rb_233.appmap.json
/Users/kgilpin/source/land-of-apps/solidus/api/tmp/appmap/rspec/Spree_Api_ProductsController_as_a_normal_user_finds_a_product_by_slug_first_then_by_id_example_at_Users_kgilpin_rbenv_versions_2_6_6_lib_ruby_gems_2_6_0_gems_appmap-0_83_3_lib_appmap_rspec_rb_233.appmap.json index version is 1.1.2
/Users/kgilpin/source/land-of-apps/solidus/api/tmp/appmap/rspec/Spree_Api_ProductsController_as_a_normal_user_finds_a_product_by_slug_first_then_by_id_example_at_Users_kgilpin_rbenv_versions_2_6_6_lib_ruby_gems_2_6_0_gems_appmap-0_83_3_lib_appmap_rspec_rb_233.appmap.json created at 1655431193238, indexed at 1655431193238
Fingerprint is up to date. Skipping...
```

### CODE REVIEW

**Comment by kgilpin** [comment]
Tests are failing: ```➤ YN0000: [@appland/appmap]: Summary of all failing tests
➤ YN0000: [@appland/appmap]: FAIL tests/unit/depends.spec.js
➤ YN0000: [@appland/appmap]:   ● Depends › indicates when a dependency is modified
➤ YN0000: [@appland/appmap]: 
➤ YN0000: [@appland/appmap]:     expect(received).toEqual(expected) // deep equality
➤ YN0000: [@appland/appmap]: 
➤ YN0000: [@appland/appmap]:     - Expected  - 3
➤ YN0000: [@appland/appmap]:     + Received  + 1
➤ YN0000: [@appland/appmap]: 
➤ YN0000: [@appland/appmap]:     - Array [
➤ YN0000: [@appland/appmap]:     -   "/tmp/tmp-6067-Hkc27Ata8jT5/user_page_scenario",
➤ YN0000: [@appland/appmap]:     - ]
➤ YN0000: [@appland/appmap]:     + Array []
➤ YN0000: [@appland/appmap]: 
➤ YN0000: [@appland/appmap]:       44 |     fn.baseDir = appMapDir;
➤ YN0000: [@appland/appmap]:       45 |     const depends = await fn.depends();
➤ YN0000: [@appland/appmap]:     > 46 |     expect(depends).toEqual([join(appMapDir, 'user_page_scenario')]);
➤ YN0000: [@appland/appmap]:          |                     ^
➤ YN0000: [@appland/appmap]:       47 |   });
➤ YN0000: [@appland/appmap]:       48 |
➤ YN0000: [@appland/appmap]:       49 |   test('indicates dependencies in an explicit list', async () => {
➤ YN0000: [@appland/appmap]: 
➤ YN0000: [@appland/appmap]:       at Object.<anonymous> (tests/unit/depends.spec.js:46:21)
➤ YN0000: [@appland/appmap]: 
➤ YN0000: [@appland/appmap]: FAIL tests/unit/fingerprint/fingerprintQueue.spec.ts
➤ YN0000: [@appland/appmap]:   ● FingerprintQueue › gracefully handles files which cannot be read
➤ YN0000: [@appland/appmap]: 
➤ YN0000: [@appland/appmap]:     expect(received).toBe(expected) // Object.is equality
➤ YN0000: [@appland/appmap]: 
➤ YN0000: [@appland/appmap]:     Expected: 1
➤ YN0000: [@appland/appmap]:     Received: 0
➤ YN0000: [@appland/appmap]: 
➤ YN0000: [@appland/appmap]:       14 |     await queue.process();
➤ YN0000: [@appland/appmap]:       15 |
➤ YN0000: [@appland/appmap]:     > 16 |     expect(logWarn.callCount).toBe(1);
➤ YN0000: [@appland/appmap]:          |                               ^
➤ YN0000: [@appland/appmap]:       17 |     expect(logWarn.getCall(0).args[0]).toMatch(/The file does not exist/);
➤ YN0000: [@appland/appmap]:       18 |   });
➤ YN0000: [@appland/appmap]:       19 | });
➤ YN0000: [@appland/appmap]: 
➤ YN0000: [@appland/appmap]:       at Object.<anonymous> (tests/unit/fingerprint/fingerprintQueue.spec.ts:16:31)
➤ YN0000: [@appland/appmap]: 
➤ YN0000: [@appland/appmap]: 
➤ YN0000: [@appland/appmap]: Test Suites: 2 failed, 28 passed, 30 total
➤ YN0000: [@appland/appmap]: Tests:       2 failed, 137 passed, 139 total
➤ YN0000: [@appland/appmap]: Snapshots:   16 passed, 16 total
➤ YN0000: [@appland/appmap]: Time:        19.107 s```

**Comment by apotterri** [comment]
These changes look ok to me, but I guess you need to figure out why the tests are failing.

**Comment by dividedmind** [comment]
Thanks for fixing this, the code is much cleaner, too!

(I was in the middle of reading the code when you merged it, but the only comments I'd have had would be re some types that could be more precisely determined.)

**Comment by kgilpin** [comment]
Sorry, I didn’t know you were looking at it

**Comment by dividedmind** [comment]
> Sorry, I didn’t know you were looking at it

No worries, I could have told you when I started :)

**Pull request merged**
