### PR TITLE
feat: show notice when empty AppMap was opened

### PR DESCRIPTION
**Pull request by sashahonchar**
**NB!** I have a feeling what we need a design for this message (with the Appland logo, explanations, etc.)

Fixes: #96 
[Figma => ](https://www.figma.com/file/BqZuGL8egIF37cgbvrz1Xm/vscode?node-id=980%3A12925)

### CODE REVIEW

**Comment by dustinbyrne** [comment]
@typaulhus can you check this out?

**Comment by typaulhus** [comment]
> @typaulhus can you check this out?

Yup! Is there a way I can see the map w/out data?

**Review by kgilpin — CHANGES_REQUESTED** [review]
@ptrdvrk this message needs to indicate some troubleshooting info to the user.

**Comment by typaulhus** [comment]
> @ptrdvrk this message needs to indicate some troubleshooting info to the user.

added

**Review by typaulhus — APPROVED** [review]

**Pull request merged**
