### PR TITLE
fix: show filter suggestions when pressing Enter in empty input

### LINKED ISSUE #504: Pressing enter in the root object/hide object inputs with no value displays the suggestion drop down

### PR DESCRIPTION
**Pull request by sashahonchar**
Fixes #504

### CODE REVIEW

**Review by dustinbyrne — CHANGES_REQUESTED** [review]
The change looks good but the behavior is lacking test coverage.

**Comment by sashahonchar** [comment]
I've added test case to make sure suggestions list is still visible after submitting empty input
https://github.com/applandinc/appmap-js/pull/508/commits/bc31813f83dec35e7d21135255981c1a9de9e484

**Comment by dustinbyrne** [comment]
Thanks! This branch needs to be rebased.

**Comment by sashahonchar** [comment]
@dustinbyrne  Just rebased

**Review by dustinbyrne — APPROVED** [review]

**Pull request merged**
