### PR TITLE
feat: initial commit

### PR DESCRIPTION
**Pull request by lachrist**
Initial version, I'm not sure I setup things correctly though. Also have not fully tested the schema yet so it might not be 100% accurate.

### CODE REVIEW

**Comment by kgilpin** [comment]
The coverage may be checked in by accident?

**Review by dustinbyrne — APPROVED** [review]
I'm having some issues validating [`scenario.json`](https://github.com/applandinc/appmap-js/blob/c4776a0514c333746846b8ffca88465f8c2739ee/packages/components/src/stories/data/scenario.json), so there's likely some more work to be done. Though I haven't dug in to verify whether it's an issue with the schema itself or a violation of the AppMap spec.

In any case, I don't want to hold this PR up. We can continue to iterate on this.

**Comment by lachrist** [comment]
I believe it is because it is version 1.3 and I validate against 1.6. I'm not sure whether I should spend some time to support legacy versions.

**Comment by lachrist** [comment]
I mean I explicitely look for `"version": "1.6"`

**Pull request merged**
